language: c

sudo: required

dist: trusty

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_r devtools
  - ./travis-tool.sh install_r knitr
  - ./travis-tool.sh install_r markdown
  - pip install dropbox
  - sudo apt-get install pandoc
  - sudo apt-get install texlive-latex-base

script:
  - Rscript -e "source('pdfProcessing.r')"
  - python upload.py

notifications:
  email: false